#!/usr/bin/env bash
#looping but repacing 4th and 8th words  with bad and good luck respectively

i=1
while [ "$i" -le 10 ]; do
  if [ "$i" -eq 4 ]; then
    echo "bad luck"
  elif [ "$i" -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((i++))
done
